DEBUG = True

USERNAME = 'sa'
PASSWORD = 'Senha'
SERVER = '00.000.0.00\SQLEXPRESS'
DB = 'BD_SERVICOS'

SQLALCHEMY_DATABASE_URI = f'mssql+pyodbc://{USERNAME}:{PASSWORD}@{SERVER}/{DB}?driver=ODBC+Driver+17+for+SQL+Server'
SQLALCHEMY_TRACK_MODIFICATIONS = True

